tag = "tags"
# person related to the subject of a page
person = "persons"
# projects related to the subject of a page
project = "projects"
# topics related to the subject of a page
topic = "topics"
dataset = "datasets"
instrument = "instruments"
objective = "objectives"
publication = "publications"
