languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Center for Open Neuroscience"
copyright = "CON website content is available under CC BY 3.0 unless otherwise noted."

[params]
  dateFormat = "2 January 2006"
  mainSections = ["projects"]
  description = "Open software frameworks, platforms, data, and methodologies for neuroscience and beyond."

[params.author]
  name = "Center for Open Neuroscience"
  headline = "Open neuroscience infrastructure, software, data, and methods."
  links = [{ github = "https://github.com/con" }]
