_merge = "none"

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10
  [main.params]
    icon = "circle-info"
    showName = true

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20
  [main.params]
    icon = "human-dolly"
    showName = true

[[main]]
  name = "People"
  pageRef = "whoweare"
  weight = 30
  [main.params]
    icon = "account-group"
    showName = true

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 50
  [main.params]
    icon = "cast-education"
    showName = true

[[main]]
  name = "Outputs"
  pageRef = "instruments"
  weight = 60
  [main.params]
    icon = "mdi-microscope"
    showName = true

[[main]]
  name = "Explore"
  pageRef = "explore"
  weight = 70
  [main.params]
    icon = "globe"
    showName = true

[[main]]
  name = "Engage"
  pageRef = "engage"
  weight = 80

[[main]]
  name = "Support"
  pageRef = "support"
  weight = 90

[[footer]]
  name = "Contact"
  pageRef = "contact"
  weight = 100
