colorScheme = "con"
defaultAppearance = "light"
autoSwitchAppearance = true
enableQuicklink = false

[header]
  layout = "hybrid"
  logo = "img/con-logo.png"
  logoDark = "img/con-logo.png"
  showTitle = true

[homepage]
  layout = "custom"
  showRecent = false

[article]
  showDate = false
  showDateUpdated = false
  showAuthor = false
  showBreadcrumbs = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = false
  showTableOfContents = false
  showTaxonomies = false
